#### 1. Replace all odd numbers in array with -2


Use the array given below

arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

In [2]:
import numpy as np
arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])
arr[arr%2 !=0 ] = -2
arr

array([ 0, -2, 42, -2, 34, -2, 26, -2, 38, 94, -2, 78, 76])

#### 2. Write a program to calculate the sum of each column

Use the array given below: (or create your own array)

A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [17]:
A = np.array([[1, 4, 8], [5, 7, 3], [9, 14, 2]]) 
np.sum(A, axis=0)

array([15, 25, 13])

	
#### 3.  Write a code to get the element-wise remainder of an array after division by 8

In [18]:
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

# convert the list to array
np.asarray(num)

array([42, 87, 90, 14, 32, 75, 61, 80, 92])