#### 1. Write a program to find BMI of the patients whose height and weight is provided in the list given below

Use the lists given below:

list of weights (in kg) weights = [57, 69, 54, 65 ,71, 62, 56]

list of heights (in m)
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53]

In [2]:
import numpy as np
weights = [57, 69, 54, 65 ,71, 62, 56]
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53]

# convert the list to array
weights = np.asarray(weights)
heights = np.asarray(heights)
# formula to calculate BMI
bmi= weights/(heights**2)
bmi


array([22.54657648, 22.53061224, 19.59645812, 21.46915048, 26.39797739,
       20.9572742 , 23.922423  ])

In [12]:
a = np.array([0, 1, 2])

b = np.array([5, 5, 5])

a + b

a + 5

array([5, 6, 7])

In [13]:
x = np.array([[3], [5], [7]])

y = np.array([[5], [7], [9]])
np.hstack((x,y))

array([[3, 5],
       [5, 7],
       [7, 9]])